//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEP520G.Dispensing.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OEP520G.Dispensing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 複製 的當地語系化字串。
        /// </summary>
        internal static string Button_CopyShape_Content {
            get {
                return ResourceManager.GetString("Button_CopyShape_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Button_DeleteShape_Content {
            get {
                return ResourceManager.GetString("Button_DeleteShape_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠測試 的當地語系化字串。
        /// </summary>
        internal static string Button_DispenseTest_Content {
            get {
                return ResourceManager.GetString("Button_DispenseTest_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠資料產生 的當地語系化字串。
        /// </summary>
        internal static string Button_DispensingSet_Content {
            get {
                return ResourceManager.GetString("Button_DispensingSet_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UV測試 的當地語系化字串。
        /// </summary>
        internal static string Button_ExecuteUvTest_Content {
            get {
                return ResourceManager.GetString("Button_ExecuteUvTest_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得Z座標 的當地語系化字串。
        /// </summary>
        internal static string Button_GetXPos_Content {
            get {
                return ResourceManager.GetString("Button_GetXPos_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得XY座標 的當地語系化字串。
        /// </summary>
        internal static string Button_GetXYPos_Content {
            get {
                return ResourceManager.GetString("Button_GetXYPos_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 膠重測試 的當地語系化字串。
        /// </summary>
        internal static string Button_GlueTest_Content {
            get {
                return ResourceManager.GetString("Button_GlueTest_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 移動Z至 的當地語系化字串。
        /// </summary>
        internal static string Button_MoveZTo_Content {
            get {
                return ResourceManager.GetString("Button_MoveZTo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 移動XY至 的當地語系化字串。
        /// </summary>
        internal static string Button_MovtXYTo_Content {
            get {
                return ResourceManager.GetString("Button_MovtXYTo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        internal static string Button_NewShape_Content {
            get {
                return ResourceManager.GetString("Button_NewShape_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 補差值 的當地語系化字串。
        /// </summary>
        internal static string Button_OffsetAdjustment_Content {
            get {
                return ResourceManager.GetString("Button_OffsetAdjustment_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預吐膠
        ///設定及測試 的當地語系化字串。
        /// </summary>
        internal static string Button_PreDispensingSetting_Content {
            get {
                return ResourceManager.GetString("Button_PreDispensingSetting_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回復原先資料 的當地語系化字串。
        /// </summary>
        internal static string Button_Restore_Content {
            get {
                return ResourceManager.GetString("Button_Restore_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定中心 的當地語系化字串。
        /// </summary>
        internal static string Button_SetCenter_Content {
            get {
                return ResourceManager.GetString("Button_SetCenter_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 畫像參數 的當地語系化字串。
        /// </summary>
        internal static string Button_VisionData_Content {
            get {
                return ResourceManager.GetString("Button_VisionData_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新品種名稱 的當地語系化字串。
        /// </summary>
        internal static string CRUD_New_NewTitle {
            get {
                return ResourceManager.GetString("CRUD_New_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立新點膠品種 的當地語系化字串。
        /// </summary>
        internal static string CRUD_New_Title {
            get {
                return ResourceManager.GetString("CRUD_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組編號 的當地語系化字串。
        /// </summary>
        internal static string DispensingActionColumn_Group {
            get {
                return ResourceManager.GetString("DispensingActionColumn_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號 的當地語系化字串。
        /// </summary>
        internal static string DispensingActionColumn_No {
            get {
                return ResourceManager.GetString("DispensingActionColumn_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠動作 的當地語系化字串。
        /// </summary>
        internal static string DispensingActionColumn_Type {
            get {
                return ResourceManager.GetString("DispensingActionColumn_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組
        ///編號 的當地語系化字串。
        /// </summary>
        internal static string DispensingParameter_Group {
            get {
                return ResourceManager.GetString("DispensingParameter_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠品種已存在:  的當地語系化字串。
        /// </summary>
        internal static string ErrorMsg_ShapeExist {
            get {
                return ResourceManager.GetString("ErrorMsg_ShapeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實際點膠 的當地語系化字串。
        /// </summary>
        internal static string Label_Dispense_Content {
            get {
                return ResourceManager.GetString("Label_Dispense_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 跟隨選擇 的當地語系化字串。
        /// </summary>
        internal static string Label_Follow_Content {
            get {
                return ResourceManager.GetString("Label_Follow_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UV後等待時間 的當地語系化字串。
        /// </summary>
        internal static string Label_UvPostWait_Content {
            get {
                return ResourceManager.GetString("Label_UvPostWait_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UV前等待時間 的當地語系化字串。
        /// </summary>
        internal static string Label_UvPreWait_Content {
            get {
                return ResourceManager.GetString("Label_UvPreWait_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UV照射時間 的當地語系化字串。
        /// </summary>
        internal static string Label_UvTime_Content {
            get {
                return ResourceManager.GetString("Label_UvTime_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 畫像檢查 的當地語系化字串。
        /// </summary>
        internal static string Label_VisionInspection_Content {
            get {
                return ResourceManager.GetString("Label_VisionInspection_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠XY軸移動速度(mm/秒) 的當地語系化字串。
        /// </summary>
        internal static string Note_DispSpeed_Content {
            get {
                return ResourceManager.GetString("Note_DispSpeed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 續吐膠時間(毫秒)；
        ///移動完等待時間後停膠 的當地語系化字串。
        /// </summary>
        internal static string Note_EShot_Content {
            get {
                return ResourceManager.GetString("Note_EShot_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停膠後等待時間接(毫秒)後再斷膠 的當地語系化字串。
        /// </summary>
        internal static string Note_EWait_Content {
            get {
                return ResourceManager.GetString("Note_EWait_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組編號 的當地語系化字串。
        /// </summary>
        internal static string Note_GroupNo_Content {
            get {
                return ResourceManager.GetString("Note_GroupNo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預停膠距離(毫秒)/角度 的當地語系化字串。
        /// </summary>
        internal static string Note_PreStop_Content {
            get {
                return ResourceManager.GetString("Note_PreStop_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 R軸點膠旋轉速度(度/秒) 的當地語系化字串。
        /// </summary>
        internal static string Note_SpeedR_Content {
            get {
                return ResourceManager.GetString("Note_SpeedR_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預點膠時間(毫秒)
        ///正值：到達點膠位置前提早出膠的時間
        ///0：到達點膠位置後再出膠
        ///負值：到達點膠位置後等待時間後再出膠 的當地語系化字串。
        /// </summary>
        internal static string Note_SWait_Content {
            get {
                return ResourceManager.GetString("Note_SWait_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 斷膠延遲時間(毫秒) 的當地語系化字串。
        /// </summary>
        internal static string Note_UpDelay_Content {
            get {
                return ResourceManager.GetString("Note_UpDelay_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 斷膠速度(mm/秒) 的當地語系化字串。
        /// </summary>
        internal static string Note_UpSpeed_Content {
            get {
                return ResourceManager.GetString("Note_UpSpeed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 斷膠方式   0：無
        ///　１：一般回移　２：方形回移 的當地語系化字串。
        /// </summary>
        internal static string Note_UpWay_Content {
            get {
                return ResourceManager.GetString("Note_UpWay_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 斷膠距離(mm)：第一次XY軸回移距離 的當地語系化字串。
        /// </summary>
        internal static string Note_UpXY_Content {
            get {
                return ResourceManager.GetString("Note_UpXY_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 斷膠高度(mm)：第一次Z軸上升高度 的當地語系化字串。
        /// </summary>
        internal static string Note_UpZ_Content {
            get {
                return ResourceManager.GetString("Note_UpZ_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠參數設定 的當地語系化字串。
        /// </summary>
        internal static string PageTitle_DispensingSetting_Text {
            get {
                return ResourceManager.GetString("PageTitle_DispensingSetting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 以相機為參考 的當地語系化字串。
        /// </summary>
        internal static string Radio_ByCamera_Content {
            get {
                return ResourceManager.GetString("Radio_ByCamera_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 以針頭為參考 的當地語系化字串。
        /// </summary>
        internal static string Radio_ByNeedle_Content {
            get {
                return ResourceManager.GetString("Radio_ByNeedle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠參數 的當地語系化字串。
        /// </summary>
        internal static string Subtitle_DispensingParameter_Text {
            get {
                return ResourceManager.GetString("Subtitle_DispensingParameter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點膠品種 的當地語系化字串。
        /// </summary>
        internal static string Subtitle_DispensingShape_Header {
            get {
                return ResourceManager.GetString("Subtitle_DispensingShape_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UV照射參數 的當地語系化字串。
        /// </summary>
        internal static string Subtitle_UvParameter_Header {
            get {
                return ResourceManager.GetString("Subtitle_UvParameter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UV照射位置 的當地語系化字串。
        /// </summary>
        internal static string UvPosition_GroupBox_Header {
            get {
                return ResourceManager.GetString("UvPosition_GroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無 的當地語系化字串。
        /// </summary>
        internal static string UvPositionNone_Content {
            get {
                return ResourceManager.GetString("UvPositionNone_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台車 的當地語系化字串。
        /// </summary>
        internal static string UvPositionStage_Content {
            get {
                return ResourceManager.GetString("UvPositionStage_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 托盤 的當地語系化字串。
        /// </summary>
        internal static string UvPositionTray_Content {
            get {
                return ResourceManager.GetString("UvPositionTray_Content", resourceCulture);
            }
        }
    }
}
